name: ritter-bot-trigger-deployment
on:
    schedule:
        - cron: "*/30 * * * *"
    push:
        branches:
            - master
jobs:
    commit:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
              with:
                  ref: deployment
            - name: save current date
              run: |
                  # Writes the current date and time to time.txt
                  date > time.txt

            - name: setup git config
              run: |
                  # setup the username and email
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: commit
              run: |
                  # Operation that changes a file in the git repo. Stage the file, commit and push
                  git checkout deployment
                  git add time.txt
                  git commit -m "new date commit to trigger deployment"
                  git push
